### ISSUE TITLE
Dapr project does not automatically build before run

### ISSUE THREAD

**Issue by oclipa** [microsoft/vs-dapr#21]
Visual Studio: Version 17.9.0 Preview 5.0
Dapr Extension: 0.1.530.1

I have created a new solution and added the dapr.yaml file:

```
apps:
- appDirPath: src\My.Project
  appID: myProject
  appPort: 8000
  command:
  - dotnet
  - run
version: 1
```

The Dapr project is marked as the Startup project.

In the Visual Studio "Build and Run" settings, it is set to "Always build".

Whenever I run, the solution does not build, I have to build manually before running.

It works fine in another solution.

Do you have any idea what the problem is?
